CREATE DATABASE QBDULICH
USE QBDULICH
CREATE TABLE TaiKhoan
(
  UserName NVARCHAR(50) NOT NULL,
  Password NVARCHAR(50) NOT NULL,
  Loai INT NOT NULL,
  PRIMARY KEY (UserName)
);

CREATE TABLE DiemThamQuan
(
	MaDD NVARCHAR(50) NOT NULL,
  Tendiadiem NVARCHAR(100) NOT NULL,
  MoTa NVARCHAR(4000) NOT NULL,
  TenFileAnh NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaDD)
);

CREATE TABLE KhachSan
(
  MaKS NVARCHAR(50) NOT NULL,
  TenKS NVARCHAR(100) NOT NULL,
  DiaChi NVARCHAR(50) NOT NULL,
  SDT NVARCHAR(50) NOT NULL,
  XepHang_KS INT NOT NULL,
  TenFIleAnh NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaKS)
);

CREATE TABLE NhanVien
(
	MaNV NVARCHAR(50) NOT NULL,
  TenNV NVARCHAR(50) NOT NULL,
  GioiTinh NVARCHAR(10) NOT NULL,
  SoDienThoai NVARCHAR(50) NOT NULL,
  DiaChi NVARCHAR(50) NOT NULL,
  UserName NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaNV),
  FOREIGN KEY (UserName) REFERENCES TaiKhoan(UserName)
);

CREATE TABLE Event
(
  MaSK NVARCHAR(50) NOT NULL,
  MoTa NVARCHAR(4000) NOT NULL,
  NoiDung NVARCHAR(4000) NOT NULL,
  TenFileAnh NVARCHAR(50) NOT NULL,
  MaNV NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaSK),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Culture
(
  MaVH NVARCHAR(50) NOT NULL,
  MoTa NVARCHAR(4000) NOT NULL,
  TenFileAnh NVARCHAR(50) NOT NULL,
  NoiDung NVARCHAR(4000) NOT NULL,
  MaNV NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaVH),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE News
(
  MaTin NVARCHAR(50) NOT NULL,
  MoTa NVARCHAR(4000) NOT NULL,
  TenFileAnh NVARCHAR(50) NOT NULL, 
  Noi_dung NVARCHAR(4000) NOT NULL,
  MaNV NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaTin),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Tour
(
  MaTour NVARCHAR(50) NOT NULL,
  TenTour NVARCHAR(100) NOT NULL,
  Anh NVARCHAR(100) NOT NULL,
  XepHangTour INT NOT NULL,
  MoTa NVARCHAR(4000) NOT NULL,
  MaNV NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaTour),
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE DiaDiemTour
(
  ViTriAnh NVARCHAR(50) NOT NULL,
  MaDD NVARCHAR(50) NOT NULL,
  MaTour NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaDD, MaTour),
  FOREIGN KEY (MaDD) REFERENCES DiemThamQuan(MaDD),
  FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);

CREATE TABLE KhachSanTour
(
  ViTriAnh NVARCHAR(50) NOT NULL,
  MaKS NVARCHAR(50) NOT NULL,
  MaTour NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MaKS, MaTour),
  FOREIGN KEY (MaKS) REFERENCES KhachSan(MaKS),
  FOREIGN KEY (MaTour) REFERENCES Tour(MaTour)
);